(set-logic ALL)
(synth-fun inv-fn ((var_i (_ BitVec 1)) (var_x (Array (_ BitVec 1) (_ BitVec 2)))) Bool)
(declare-var var_x (Array (_ BitVec 1) (_ BitVec 2)))
(declare-var var_x! (Array (_ BitVec 1) (_ BitVec 2)))
(declare-var var_i (_ BitVec 1))
(declare-var var_i! (_ BitVec 1))
(define-fun init-fn ((var_i (_ BitVec 1)) (var_x (Array (_ BitVec 1) (_ BitVec 2)))) Bool (= var_x (store (store var_x (_ bv0 1) (_ bv1 2)) (_ bv1 1) (_ bv1 2))))
(define-fun trans-fn ((var_i (_ BitVec 1)) (var_x (Array (_ BitVec 1) (_ BitVec 2))) (var_i! (_ BitVec 1)) (var_x! (Array (_ BitVec 1) (_ BitVec 2)))) Bool (and (= var_i! var_i) (= var_x! var_x)))
(define-fun post-fn ((var_i (_ BitVec 1)) (var_x (Array (_ BitVec 1) (_ BitVec 2)))) Bool (forall ((index (BitVec 1)))  (bvsge (select var_x index) (_ bv1 2))))
(constraint (=> (init-fn var_i var_x) (inv-fn var_i var_x)))
(constraint (=> (and (inv-fn var_i var_x) (trans-fn var_i var_x var_i! var_x!)) (inv-fn var_i! var_x!)))
(constraint (=> (inv-fn var_i var_x) (post-fn var_i var_x)))
(check-synth)
