/*
 * UCLID5 Verification and Synthesis Engine
 *
 * Copyright (c) 2017.
 * Sanjit A. Seshia, Rohit Sinha and Pramod Subramanyan.
 *
 * All Rights Reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *
 * this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 *
 * documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Author: Ofek Shani
 *
 * Compute the GNBA's correspoinding to each LTL formula in a module and combine them in lockstep with the TS
 *
 * This approach is based on the automata-theoretic approach to LTL verification. Process is as follows:
 * For each LTL formula in the inputted Transition System (TS), construct a Generalized Nondeterministic Buchi Automata
 * (GNBA) representing its negation (aka a GNBA for the formula's forbidden cases).
 * Then, run that formula in lockstep with the TS (here we combine the modules).
 * If both modules accept, then there exists a trace that satisfies the TS AND contains a forbidden case by the formula.
 *
 */

package uclid
package lang

import com.typesafe.scalalogging.Logger
// below imports are necessary for spot string conversion function
import scala.collection.mutable.Stack
import scala.collection.mutable.ArrayBuffer
import scala.sys.process._
import scala.util.parsing.combinator._
import scala.util.matching.Regex

class LTLAutomataConnector(val mainModuleName: Identifier)
    extends ASTRewriter(
      "LTLAutomataConnector",
      new LTLAutomataConnectorPass(mainModuleName)
    )

/** Connects all of the Automata Modules (generated by LTLAutomataGenerator) to
  * the main module. Marks certain variables as outputs or shared vars, and
  * removes existing LTL Specs
  *
  * TODO: While passes seem to operate on all modules, we only want this to
  * operate on main... so I put a check in the start of the rewrite function
  * that ends the function early if the module is not main module... very
  * scuffed, need to fix at some point
  */
class LTLAutomataConnectorPass(val mainModuleName: Identifier)
    extends RewritePass {

  // TODO: This pass runs on all modules -- we are going to only run this pass if the module's ID is the main one
  override def rewriteModule(module: Module, ctx: Scope): Option[Module] = {
    // only run the connector if this is the main module
    if (module.id != mainModuleName) return Some(module)

    val moduleSpecs = module.decls.collect { case spec: SpecDecl => spec }
    val ltlSpecs =
      moduleSpecs.filter(s => ExprDecorator.isLTLProperty(s.params))
    val ltlSpecIds =
      ltlSpecs.map(s => LTLAutomataGenerator.getAutomataIDFromSpec(s))
    // this expression is mostly lifted right from ModuleFlattener -- should allow us to get automataModules using just the ID's
    // TODO: We need to stop using Identifiers and start using the NameProvider system -- there has to be some other way to do this
    val automataIdentifiers =
      ltlSpecIds.map(id => ctx.map.find(p => p._1.name == id.name))
    val automataModules =
      automataIdentifiers.map(_.get._2.asInstanceOf[Scope.ModuleDefinition].mod)
    return Some(instantiateAutomataInMain(module, automataModules))
  }

  // "instantiates" each automata in automataModules inside of the main function by doing the following:
  // 1: Place a module instantiation decl in main
  // 2: Insert a ModuleCallStmt (a "next" call) for the automata in main's 'next' decls.
  // 3: Delete the automata's corresponding LTLProperty SpecDecl from main (aka. delete all LTLProperty SpecDecls from main)
  // This is done for all automata modules.
  def instantiateAutomataInMain(
      main: Module,
      automataModules: List[Module]
  ): Module = {

    // create automata instances
    val instanceDecls: List[InstanceDecl] = automataModules.map(aM =>
      InstanceDecl(
        instanceId = Identifier(aM.id.toString() + "_instance"),
        moduleId = aM.id,
        // args are input pairs -- input 1 is an inputvar in the instance, arg2 is var the caller gives.
        // the vars in the automata share the same ID as those in main, so we can just pass them in easily
        arguments = aM.inputs.map(_._1).map(id => (id, Some(id))),
        instType = None,
        modType = None
      )
    )

    // Create Automata Next calls
    val nextCalls: List[Statement] = automataModules.map(aM =>
      ModuleCallStmt(Identifier(aM.id.toString() + "_instance"))
    )

    // get the nextDecl
    val nextOpt: Option[NextDecl] = main.decls.collectFirst {
      case nd: NextDecl => nd
    }

    // Create a new NextDecl (either copy and mod existing or make new one)
    //   that contains our 'next' calls.
    val newNextDecl: NextDecl = nextOpt match {
      case Some(decl) => {
        val newBody = decl.body match {
          // a Next block with multiple stmts exists. Add the calls to it!
          case BlockStmt(nextVars, nextStmts) =>
            BlockStmt(nextVars, nextStmts ++ nextCalls)
          // Next block exists but it is just 1 Stmt. Wrap it (and our calls) into a BlockStmt!
          case otherStmt =>
            BlockStmt(Nil, List(otherStmt) ++ nextCalls)
        }
        NextDecl(newBody)
      }
      // if none, no Next block exists. Make our own and fill it with our calls.
      case None => NextDecl(BlockStmt(Nil, nextCalls))
    }

    // define new set of decls for main
    // - remove any existing NextDecl
    // - remove all LTLProperty SpecDecls
    // - append our new/modified NextDecl
    // - add the instantiation calls for our automata
    val filteredDecls: List[Decl] = main.decls.filterNot {
      case _: NextDecl => true // drop
      case SpecDecl(_, _, params) if ExprDecorator.isLTLProperty(params) =>
        true // drop
      case _ => false // keep
    }
    val newDecls = filteredDecls ++ instanceDecls ++ List(newNextDecl)
    return Module(
      id = main.id,
      decls = newDecls,
      cmds = main.cmds,
      notes = main.notes
    )
  }

  /** UNUSED: Outputs a rewritten version of origin such that every variable
    * declaration in it that shares an Identifier with an Input var in the
    * automata module is rewritten as either an output or a sharedvar (former if
    * statevar, latter if input)
    *
    * Designed to prepare a main module for being linked to an automata module.
    */
  def connectModules(origin: Module, automata: Module): Module = {
    // println("Ofek Debug: " + origin.decls.length)
    /** Steps: 
      * 1: Identify all variables in the automata module that need to be
      * copied in. (look for all 'input' vars, module function imports, module
      * synth function imports) (maps of these can be found in
      * origin.moduleType) 
      * 2: Switch all 'vars' that we need from main module
      * into an output-okay form. (if a needed var is a normal var, make it an
      * output var) (if a needed var is an input var, make it a shared var) (if
      * a needed var is already an output var, leave it as-is) 
      * 3: TODO: Something, something, functions. Somehow we need to be able to do this,
      * but I don't know how.
      */

    // 1: Get set of needed identifiers in automata module
    val wantedIdentifiers: List[Identifier] = automata.inputs.map(_._1)

    // 2: We need to create a new Module to assign to the old one that will have the necessary vars set as outputs
    //    We can access the decls -- for each decl that has an identifier that we want, change it to Output or Shared.
    //    If the decl is not one we need, we'll leave it as-is.
    //    We will only need to modify wanted vars in Input or State var decls -- Output and Shared are already outputting
    val newDecls: List[Decl] = origin.decls.flatMap {
      case StateVarsDecl(ids, typ) =>
        val (convert, keep) = ids.partition(wantedIdentifiers contains)
        val keepDecls =
          if (keep.nonEmpty) Some(StateVarsDecl(keep, typ)) else None
        val convertedDecls =
          if (convert.nonEmpty) Some(OutputVarsDecl(convert, typ)) else None
        List(keepDecls, convertedDecls).flatten // return combined list
      case InputVarsDecl(ids, typ) =>
        val (convert, keep) = ids.partition(wantedIdentifiers contains)
        val keepDecls =
          if (keep.nonEmpty) Some(SharedVarsDecl(keep, typ)) else None
        val convertedDecls =
          if (convert.nonEmpty) Some(InputVarsDecl(convert, typ)) else None
        List(keepDecls, convertedDecls).flatten // return combined list
      case otherDecl => List(otherDecl)
    }

    // Now return the original module but with the new decls...
    val toReturn = Module(origin.id, newDecls, origin.cmds, origin.notes)
    // println("Ofek Debug -- post connection module: " + toReturn.toString())
    return toReturn
  }
}

/** In order to construct the GNBA of a formula, we use the external tool "Spot"
  * https://spot.lre.epita.fr/ Specifially we use the LTL2TGBA command provided
  * by it.
  */
object SpotInterface {
  /** 
    * Print out an Expression instance in a Spot-friendly manner
    * (Spot can only support LTL and Boolean operators, Expr subtrees containing 
    * forbidden Operators are wrapped in quotes so that Spot sees the sub-expression as a variable)
    */
  def rewriteFormulaForSpot(formula: Expr): String = {
    
    /**
     * LTL Operators
     *  - GloballyTemporalOp (G)
     *  - NextTemporalOp (X)
     *  - UntilTemporalOp (U)
     *  - FinallyTemporalOp (F)
     *  - ReleaseTemporalOp (R)
     *  - WUntilTemporalOp (W)
     * 
     * Boolean Operators -- these can be unquoted, but need to be rewritten to Spot's
     *    ... preferred syntax.
     *  - ConjunctionOp ("&&", changed to "&")
     *  - DisjunctionOp ("||", changed to "|")
     *  - NegationOp ("!", kept unchanged.)
     *  - IffOp ("<==>", changed to "<->")
     *  - ImplicationOp ("==>", changed to "->")
     *  - The "XOR" operator is also technically allowed, but I can't find it in the language file. (TODO)
     * 
     * Technically, opening and closing parenthesis "()" are allowed, too.
     * 
     * Everything else (including Identifiers) will need to be wrapped in quotes.
     *  (If we don't wrap Identifiers, then an ID like "Glances" would be interpreted as "G(lances)")
     */

    object QuotedExprPrinter {
      // We use this to eliminate quotes within quotes
      // (also, helps protect from stringlits messing things up, as they use \")
      private def quote(s: String): String =
        "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

      // recursively traverses the expression, calling itself.
      // Will ID all unquoteable expressions and quote all quoteable expressions
      def print(e: Expr): String = e match {
        // boolean logic
        case OperatorApplication(NegationOp(), List(x)) => 
          "!(" + print(x) + ")"

        case OperatorApplication(ConjunctionOp(), ops) =>
          "(" + ops.map(print).mkString(" & ") + ")"

        case OperatorApplication(DisjunctionOp(), ops) =>
          "(" + ops.map(print).mkString(" | ") + ")"

        case OperatorApplication(ImplicationOp(), List(a, b)) =>
          "(" + print(a) + " -> " + print(b) + ")"

        case OperatorApplication(IffOp(), List(a, b)) =>
          "(" + print(a) + " <-> " + print(b) + ")"

        // LTL
        case OperatorApplication(GloballyTemporalOp(), List(x)) =>
          "G(" + print(x) + ")"

        case OperatorApplication(FinallyTemporalOp(), List(x)) =>
          "F(" + print(x) + ")"

        case OperatorApplication(NextTemporalOp(), List(x)) =>
          "X(" + print(x) + ")"

        // Print binary temporal ops infix to avoid commas outside quotes
        case OperatorApplication(UntilTemporalOp(), List(a, b)) =>
          "(" + print(a) + " U " + print(b) + ")"

        case OperatorApplication(ReleaseTemporalOp(), List(a, b)) =>
          "(" + print(a) + " R " + print(b) + ")"

        // include only if you want W outside quotes too
        case OperatorApplication(WUntilTemporalOp(), List(a, b)) =>
          "(" + print(a) + " W " + print(b) + ")"

        // everything else becomes a quoted atom (captures [], ==, <, +, ., function calls, etc.)
        case _ =>
          quote(e.toString)
      }
    }

    return QuotedExprPrinter.print(formula)
  }

  /** returns the HOA representation of a TGBA created from the LTL formula in
    * the inputted Expression. Output is in the form of a string following the
    * HOA format (see https://spot.lre.epita.fr/oaut.html for details)
    */
  def runLTL2TGBA(formula: Expr): String = {

    val spotFormula: String = rewriteFormulaForSpot(formula)
    val spotCommand: Seq[String] =
      Seq("/home/oshani/usr/bin/ltl2tgba", "-B", "-f", spotFormula)
    val processBuilder: ProcessBuilder = spotCommand
    println(
      "Ofek Debug: converted " + formula.toString() + " to " + spotFormula
    )
    val toReturn: String = processBuilder.!!
    return toReturn
  }
}

object LTLAutomataGenerator {

  val LTLAUTOMATA_ID_PREFIX = "__automata__"
  // returns the Identifier of the automata generated from a given SpecDecl (should only be used on LTL formulas)
  def getAutomataIDFromSpec(s: SpecDecl): Identifier = Identifier(
    LTLAUTOMATA_ID_PREFIX + s.id.toString()
  )

  /** Utility function. Traverses the given expression and returns all
    * Identifiers found within as a set. TODO: This function needs testing to
    * ensure that it fully works -- I had to rely on AI heavily to implement
    * it...
    */
  def getIdentifiersInExpression(e: Expr): Set[Identifier] = {
    def go(exp: Expr): Set[Identifier] = exp match {
      /* literals */
      case _: Literal => Set.empty
      /* plain identifier ------------------------------------------------ */
      case id @ Identifier(_)        => Set(id)
      case ExternalIdentifier(_, id) => Set(id)

      /* quantifiers (forall/exists) ------------------------------------ */
      case OperatorApplication(ForallOp(vs, _), List(arg)) =>
        go(arg) -- vs.map(_._1) // handled *before* generic OA
      case OperatorApplication(ExistsOp(vs, _), List(arg)) =>
        go(arg) -- vs.map(_._1)

      /* operator / function application -------------------------------- */
      case OperatorApplication(_, args) => args.flatMap(go).toSet
      case FuncApplication(fun, args)   => go(fun) ++ args.flatMap(go)

      /* tuples, arrays, records ---------------------------------------- */
      case Tuple(elems)          => elems.flatMap(go).toSet
      case ConstArray(defVal, _) => go(defVal)
      case ConstRecord(fields)   =>
        fields.flatMap { case (_, v) => go(v) }.toSet

      /* let / lambda — remove bound names ------------------------------ */
      case LetExpr(defs, body) =>
        val bound = defs.map(_._1.asInstanceOf[Identifier]).toSet
        defs.flatMap { case (_, rhs) => go(rhs) }.toSet ++ go(body) -- bound

      case Lambda(params, body) =>
        go(body) -- params.map(_._1)
    }

    go(e)
  }

  // generates all the automata for a given module, each representing the negation of one of the
  // ltl properties in the module. BIG TODO.
  def generateAllAutomata(
      modules: List[Module],
      mainModuleName: Identifier
  ): List[Module] = {
    // Step 0: ID the main module. If we can't find it, throw an error.
    val mainModule = modules.find(_.id == mainModuleName)
    mainModule match {
      case Some(module) =>
        // Step 1: Extract all the LTL specs from the module, extract and negate each expression, and convert into an automata.
        // Recall that we negate the expression in order to get an expression representing the cases forbidden by the property we want to verify.
        // Our automata only "accept" if they never actually reach an acceptance state, so each module essentially verifies "not forbidden state".
        val moduleSpecs = module.decls.collect { case spec: SpecDecl => spec }
        val ltlSpecs =
          moduleSpecs.filter(s => ExprDecorator.isLTLProperty(s.params))
        val negatedProperties: List[Expr] =
          ltlSpecs.map(s => OperatorApplication(NegationOp(), List(s.expr)))
        // Step 2: Convert into LTL Automata!
        // Filter out any that fail to be assembled, then return.
        val automataModules: List[Module] =
          ltlSpecs.map(s => constructAutomataModule(module, s)).flatten
        return automataModules
      case None =>
        throw new Utils.ParserError(
          "Unable to find main module (from LTLAutomataGenerator)",
          None,
          None
        )
    }

  }

  /** Class containing the raw state, conditional, and transition data used to
    * make the automata. Note: A lot of the stuff here is generated through
    * manual string processing. HOA has an official spec containing its regular
    * grammer -- this could be reworked to fully use parsers for it
    */
  class HOAData(module: Module, spotTGBA: String) {
    private val metadata = spotTGBA.split("--BODY--\n", 2)(0)
    private val metadataLines = metadata.split('\n')
    private val body = spotTGBA.split("--BODY--\n", 2)(1)

    // the number of states in the automata
    val numStates: Option[Int] = getDataFromField("States").map(_.toInt)

    // the initial state for the automata
    val initialStates: Option[Set[Int]] = getDataFromField("Start").map(
      statesStr => statesStr.split("&").map(_.toInt).toSet
    )

    // Array of AP's that the automata uses
    // TODO: Make sure you can actually split the strings this way -- this seems off
    val atomicExpressions: Option[Array[Expr]] =
      getDataFromField("AP").map(apStr => {
        // split into individual AP strings -- at this point each AP in the string is surrounded by quotes
        val strs = apStr.split(" ", 2)(1)
        // split into individual AP's by splitting by quotes and filtering out empty strings
        val noQuotes =
          strs.split("\"").filter(s => !s.equals(" ") && !s.equals(""))
        noQuotes.map(ExprParser(_))
      })

    // A set of all variable Identifers in the TS module that are used by the AP's
    // to obtain: extract all of the variavles in the atomics, and get their types from the module, create all the var decls for them
    val moduleVarIdentifiers: Option[Set[Identifier]] = atomicExpressions
      .map(_.map(getIdentifiersInExpression(_)))
      .map(_.reduce(_ union _))

    private val transStrings: Array[String] =
      body.dropRight(8).split("State: ").filter(_ != "")

    // An array of all acceptance sets for the GNBA. Recall that each acc set must be visited infinite for the
    // automata module to accept
    val acceptSets
        : Option[Array[Set[Int]]] = getDataFromField("Acceptance").map(asc => {
      // Acceptance field is in the form "[#acceptsets] [acceptconds]", so we isolate the number
      var sets = Array.fill(asc.split(" ")(0).toInt)(Set[Int]())
      transStrings.foreach(s => {
        val lines = s.split('\n')
        // get state num
        val stateNum = lines(0).split(" ")(0).toInt
        // state header is [statenum] {acc_set_1 acc_set_2 ...} -- the {} only appears if there are any sets it's a part of
        val setsWithState =
          if (lines(0).contains('{'))
            lines(0)
              .split(" ", 2)(1) // isolate {...}
              .filter(c => !("{}".contains(c))) // remove {, }
              .split(" ") // turn into arr
              .map(_.toInt)
          else Array[Int]()
        setsWithState.foreach(aSet => sets(aSet) += stateNum)
      })
      if (sets.size > 1)
        System.err.println(
          "ERROR: Spot output contains more than 1 acceptance set!\n" + spotTGBA
        )
      sets
    })

    private val spotParser =
      atomicExpressions.map(aIds => new SpotCondMiniParser(aIds))

    /** The transition function -- A list of the lists of transitions (Expr
      * representing requirement and List[int] representing sets of destination
      * states) for each state Each transition consists of the condition
      * required, as well as the set of states that transition connects to
      */
    val transitionsRaw: Option[List[List[(Expr, List[Int])]]] = spotParser.map {
      parser =>
        transStrings.zipWithIndex.toList.map { case (str, idx) =>
          // isolate all non-header lines of the state. Each line contains a condition and the states to go to if that condition is met.
          val lines = str.split('\n').drop(1)
          // set up list of transitions for the current state
          val pairList: List[(Expr, List[Int])] = lines.toList.map { s =>
            val condStr: String = s.slice(s.indexOf('[') + 1, s.indexOf(']'))
            val condExpr: Expr = parser.parse(condStr)
            val destinationStateStrings: List[String] = s
              .substring(s.indexOf(']') + 1)
              .split(" ")
              .toList
              .filter(!_.isEmpty())
            val destinationStates: List[Int] =
              destinationStateStrings.map(_.toInt)
            val listElt: (Expr, List[Int]) = ((condExpr, destinationStates))
            listElt
          }
          pairList
        }
    }

    // returns the data string of metadataLines at a certain field
    def getDataFromField(toFind: String): Option[String] = {
      val lineIndex = metadataLines.find(_.split(":")(0) == toFind)
      val toReturn = lineIndex.map(_.split(": ", 2)(1))
      return toReturn
    }

    /** A small scale parser designed to turn a Spot conditional to a BlockStmt we can use in Next Block
      * label-expr ::= BOOLEAN | INT | ANAME | "!" label-expr
      *            | "(" label-expr ")"
      *            | label-expr "&" label-expr
      *            | label-expr "|" label-expr
      * atomics is the list of AP vars used by the module
      */
    class SpotCondMiniParser(atomics: Array[Expr]) extends RegexParsers {
      override val whiteSpace: Regex = """[ ]+""".r
      val unsigInt: Regex = """[0-9]+""".r

      private def boolLit: Parser[Expr] = ("t" | "f") ^^ { b =>
        BoolLit(b == "t")
      }

      // translate numeric values to corresponding atomics
      private def intAtom: Parser[Expr] = unsigInt ^^ { num =>
        val idx = num.toInt
        if (idx > -1 && idx < atomics.length) atomics(idx)
        else sys.error(s"AP number $num not declared in AP: Line")
      }

      // recall precedence is ! > () > & > |
      // handle !, ()
      private def atom: Parser[Expr] =
        "!" ~> atom ^^ { e => Operator.not(e) } |
          "(" ~> expr <~ ")" | intAtom | boolLit

      // & operator
      private def conj: Parser[Expr] =
        rep1sep(atom, "&") ^^ { _.reduceLeft(Operator.and) }
      // | operator
      private def expr: Parser[Expr] =
        rep1sep(conj, "|") ^^ { _.reduceLeft(Operator.or) }

      def parse(condition: String): Expr = {
        parseAll(expr, condition) match {
          case this.Success(res, _)      => res
          case this.NoSuccess(msg, next) =>
            sys.error(s"parse error at ${next.pos}: $msg")
        }
      }
    }

    /** Utility that converts a string containing exactly one UCLID-5 expression
      * into the corresponding AST node (`Expr`).
      *
      * Throws `Utils.SyntaxError` if the text is not a legal expression.
      * WARNING/TODO: This is an AI-written function. It still needs to be
      * checked.
      */
    object ExprParser {
      def apply(text: String, fileName: String = "<input>"): Expr = {

        /* 1. Tokenise the input with the lexical analyser that already
         *    belongs to UclidParser.  Note the required `new` in front of
         *    `lexical.Scanner`.                                           */
        val scanner = new UclidParser.lexical.Scanner(text)

        /* 2. Packrat combinators need a `PackratReader`.                  */
        val tokens = new UclidParser.PackratReader(scanner)

        /* 3. Parse the complete token stream with the `Expr` non-terminal
         *    (`phrase` insists that the whole input is consumed).         */
        UclidParser.phrase(UclidParser.Expr)(tokens) match {
          case UclidParser.Success(ast, _)      => ast // <- the Expr
          case UclidParser.NoSuccess(msg, next) =>
            throw new Utils.SyntaxError(msg, Some(next.pos), Some(fileName))
        }
      }
    }
  }

  /** Class with methods that, given an Identifier, return the corresponding
    * type of that Identifier in the module 'origin', if it exists. Also
    * contains method to write a declaration that takes the Identifier as an
    * input var of the right type
    */
  class VariableTypeIdentifier(origin: Module) {
    // these are the possible types that need to be handled
    sealed trait SymbolKind {
      // Whether or not the type requires an explicit declaration.
      // if false, then this type can "safely" be None.
      def needsDecl: Boolean
    }
    // These require an explicit 'input' or 'const' declaration
    case object Input extends SymbolKind { val needsDecl = true }
    case object Output extends SymbolKind { val needsDecl = true }
    case object StateVar extends SymbolKind { val needsDecl = true }
    case object SharedVar extends SymbolKind { val needsDecl = true }
    case object ConstantLit extends SymbolKind { val needsDecl = true }
    case object Constant extends SymbolKind { val needsDecl = true }

    // These are handled by wildcard imports (type * = main.*; etc)
    case object EnumConstant extends SymbolKind { val needsDecl = false }
    case object CustomType extends SymbolKind { val needsDecl = false }
    case object Function extends SymbolKind { val needsDecl = false }
    case object SynthFunc extends SymbolKind { val needsDecl = false }

    // These should be ignored or are errors
    case object Instance extends SymbolKind { val needsDecl = false }
    case object Unknown extends SymbolKind { val needsDecl = false }

    

    // returns a SymbolKind indicating the Type of node in module "m" has the id "id"
    def classify(id: Identifier): SymbolKind = {
      val mt = origin.moduleType

      if (mt.inputMap contains id) Input
      else if (mt.outputMap contains id) Output
      else if (mt.sharedVarMap contains id) SharedVar
      else if (mt.varMap contains id) StateVar
      else if (mt.constLitMap contains id) ConstantLit
      else if (mt.constantMap contains id) Constant
      else if (mt.funcMap contains id) Function
      else if (mt.synthFuncMap contains id) SynthFunc
      else if (mt.instanceMap contains id) Instance
      else if (origin.typeDeclarationMap contains id)
        CustomType // TypeDecl is used already and Type is reserved word...
      else if ((Scope.empty + origin).get(id).exists(_.isInstanceOf[Scope.EnumIdentifier])) EnumConstant
      else Unknown
    }

    def findTypeDeclForEnumConstant(id: Identifier): Option[TypeDecl] = {
      origin.decls.collectFirst {
        case td @ TypeDecl(_, EnumType(ids)) if ids.contains(id) => td
      }
    }

    def getOriginalType(id: Identifier): Type = {
      origin.decls.collectFirst {
        case d: InputVarsDecl if d.ids.contains(id) => d.typ
        case d: StateVarsDecl if d.ids.contains(id) => d.typ
        case d: OutputVarsDecl if d.ids.contains(id) => d.typ
        case d: SharedVarsDecl if d.ids.contains(id) => d.typ
        case d: ConstantsDecl if d.ids.contains(id) => d.typ
      }.getOrElse(origin.moduleType.typeOf(id).get)
    }

    // Given an ID of something in the main module, this will return a statement that can be used to copy it to somewhere else.
    // This will return a decl (input/shared var decl, constlit, import) depending on the var with the given ID.
    def toImportDecl(id: Identifier): Option[Decl] = {
      val mt = origin.moduleType
      val kind = classify(id)
      // if we don't need a Decl for this type, then we can safely return none!
      if (!kind.needsDecl) return None

      kind match {
        // all "var" types need to be fed as Inputs
        case Input | Output | StateVar | SharedVar =>
          val t = getOriginalType(id)
          Some(InputVarsDecl(List(id), t))
        // we can just declare constants outright
        case ConstantLit => // constant literals (ex: 'const k = 5')
          Some(ConstantLitDecl(id, mt.constLitMap(id)))
        case Constant => // named constant -- don't really know how this differs from ConstantLit
          Some(ConstantsDecl(List(id), mt.constantMap(id)))
        // functions will need to be imported
        case Function =>
          Some(ModuleFunctionsImportDecl(origin.id))
        case SynthFunc =>
          Some(ModuleSynthFunctionsImportDecl(origin.id))
        // TODO: If there is any type missing, add it here.
        case _ => None
      }
    }

    
  }

  /** @brief
    *   Constructs the Procedure block that updates the value of the transition
    *   bits. Modifies transitionBits such that bit "i" is a 1 if and only if
    *   there exists a valid (and take-able) transition to... ... the i-th state
    *   from the current state.
    * @param hoaData:
    *   the HOAData instance being used to genereate the automata module.
    * @param currentStateIdentifier:
    *   The identifier assigned to the currentState variable in the automata.
    * @param transitionBitsIdentifier:
    *   The identifier of the transitionBits data structure we need to fill in.
    * @param procName
    *   The identifier to assign the procedure name ID to.
    */
  def constructTransitionBuilderProcedure(
      hoaData: HOAData,
      currentStateIdentifier: Identifier,
      procName: Identifier
  ): Option[ProcedureDecl] = {
    // 1. Identifiers
    val argName = Identifier("current_state")
    val returnBitsId = Identifier("transition_bits_return")

    // 2. Procedure Signature
    // ProcedureSig(inParams: List[(Identifier,Type)], outParams: List[(Identifier,Type)])
    val params: Option[List[(Identifier, Type)]] =
      hoaData.moduleVarIdentifiers.map(_.map(id => (id, BooleanType())).toList)
    // Construct the procedure header!
    // Params is the set of atomics that Spot Identified (they are vars passed into the module)
    // the output param is the transition bitvector that we're going to build
    val sig: Option[ProcedureSig] = for {
      params <- params
      numStates <- hoaData.numStates
    } yield ProcedureSig(
      inParams = params,
      outParams = List(
        (returnBitsId, BitVectorType(numStates))
      ) // List((returnBitsId, BitVectorType(numStates)))
    )

    // 3. Modifies Set
    // Must be a Set of ModifiableEntity (usually ModifiableId)
    val modifiesSet = Set[ModifiableEntity]()

    // 4. Preconditions (Requires) & Postconditions (Ensures) -- Empty for now
    val reqs = List(
    )
    val ens = List(
    )

    val updateTransitionBits: Option[List[Statement]] =
      hoaData.transitionsRaw.map(tRaw =>
        tRaw.zipWithIndex.map { case (stateTrans, stateNum) =>

          // Only run state n's checks if we're on state n.
          val stateComparison = OperatorApplication(
            EqualityOp(),
            List(currentStateIdentifier, IntLit(stateNum))
          )
          val perStateTransition: List[IfElseStmt] =
            stateTrans.map { case (cond, dests) =>
              // now it's per edge
              // list of statements that turn on all destinations of the edge
              val enableTransitions = dests.map(ds =>
                AssignStmt(
                  List(
                    LhsSliceSelect(
                      returnBitsId,
                      ConstBitVectorSlice(ds, ds)
                    )
                  ),
                  List(BitVectorLit(1, 1))
                )
              )
              IfElseStmt(cond, BlockStmt(Nil, enableTransitions), SkipStmt())
            }
          IfElseStmt(
            stateComparison,
            BlockStmt(Nil, perStateTransition),
            SkipStmt()
          )

        }
      )

    val body: Option[BlockStmt] = updateTransitionBits.map(f =>
      BlockStmt(
        vars = List.empty,
        stmts = f
      )
    )

    // 6. Annotations (e.g., [inline] or [noinline])
    // ProcedureAnnotations(ids : Set[Identifier])
    val anns = ProcedureAnnotations(Set.empty)

    val procedureToReturn: Option[ProcedureDecl] =
      for {
        sig <- sig
        body <- body
      } yield ProcedureDecl(
        id = procName,
        sig = sig,
        body = body,
        requires = reqs,
        ensures = ens,
        modifies = modifiesSet,
        annotations = anns
      )

    return procedureToReturn
  }

  /** Constructs a UCLID representation of a generalized nondeterministic Buchi
    * Automata based on an LTL spec originModule - the UCLID module which
    * contains the formula we want to check spec - an LTL Spec describing the
    * property that originModule should follow.
    *
    * Note: The returned automata module currently has ID automata_[spec.name]
    * -- this value is used in order to filter out automata modules in the
    * automataConnectorPass.
    */
  def constructAutomataModule(
      originModule: Module,
      spec: SpecDecl
  ): Option[Module] = {

    val spotTGBA: String = SpotInterface.runLTL2TGBA(spec.expr)
    // print("Ofek Debug: Origin Module")
    print(originModule.toString())
    // Top level process is as follows:
    // 0: parse HOA format -- isolate substrings with info on states, transitions, acceptance, etc
    // 1: Define variables
    // 1a: Define automata-specific vars (current_state)
    // 1b: identify vars/funcs the module needs to compute the AP's and define their imports/inputs
    // 2: Define the init block using InitDecl (just define the inital states for all bools)
    // 3: Create the next block using NextDecl (use the transition portion of Spot Output)
    // 3.5: Create property for the automaton to follow (never hit an accept state)
    // 4: assemble the module

    // Step 0 -- we do this using the HOAData class.
    val hoaData = new HOAData(originModule, spotTGBA)

    /** 1: Define the state and input variables, function imports, constant
      * decls, etc.
      */

    // Tool for getting the types of a var in a module given its identifier.
    // used in order to get all of the imported elements needed in the automata module

    // list of input var, function import, constant and type def declarations
    // should handle everything that we need from the TS module in order to run everything smoothly

    // BIIIIG TODO: if we use enums, they are considered Identifiers and rolled into here.
      // we need a way to differentiate enumeration values from normal Identifiers, and treat them differently
    val mapper = new VariableTypeIdentifier(originModule)
    val typeImportDecl = ModuleTypesImportDecl(originModule.id)
    val compatVarDecls: Option[List[Decl]] = hoaData.moduleVarIdentifiers
      .map(ids => ids.flatMap{id => 
        val decl = mapper.toImportDecl(id)
        val kind = mapper.classify(id)
        if(decl.isEmpty && kind.needsDecl) {
          System.err.println(s"Error: Failed to generate required declaration for ${id} (Kind: ${kind})")
        }
        decl // the return stmt
      }.toList.distinct)
      

    val currentState = Identifier(spec.id + "_current_state")
    val currentStateVarDecl = StateVarsDecl(List(currentState), IntegerType())

    /** 2: Module Init Block TLDR: nondeterministically select the init state
      * from the set of possible init states
      */

    // init state setting
    val initStateHavoc = HavocStmt(HavocableId(currentState))
    // assume initial currentState == [initStates(0)] or == initStates(1) or ...
    // this is literally a giant conjunction of equality checks. We could use a bitvector like in the next block
    // but that's going to be messier (probably)
    val initStateAssume: Option[AssumeStmt] =
      hoaData.initialStates.map(states =>
        AssumeStmt(
          OperatorApplication(
            DisjunctionOp(),
            states
              .map(s =>
                OperatorApplication(EqualityOp(), List(currentState, IntLit(s)))
              )
              .toList ++ List(BoolLit(false))
          ),
          None
        )
      )
    // TODO: DisjunctionOp needs at least 2 params, so I added the extra 'false' as a noncontrolling input
    // to keep things working when there is only 1 initial state. This solution is... pretty bad. I'm not going su sugarcoat.
    // Once the MVP is done, this needs to be fixed.

    val initDecl: Option[InitDecl] =
      for {
        initStateAssume <- initStateAssume
      } yield InitDecl(
        BlockStmt(Nil, List(initStateHavoc, initStateAssume))
      ) // both are Decl, list type is Decl

    /** 3: Module Next Block (this one is a bit confusing) TLDR: evaluate all of
      * the conditions for edges. Keep track of the destinations we can go to
      * using a bitvector and then nondeterministically select the next state
      * from set of possible destinations
      */

    // we keep the set of valid transitions from the current state as a local bit vector, where each bit
    // in the vector represents a state.
    // if a state's corresponding bit is 1, there exists a traverable transition from the current state to that state.
    val transitionBits = Identifier("validTransitions")
    val transitionBitsDecl = hoaData.numStates.map(n =>
      BlockVarsDecl(List(transitionBits), BitVectorType(n))
    )

    // define the update Transition Bits Function
    val updateTransitionBitsId: Identifier = Identifier(
      "get_next_states"
    )
    // Defines the procedure that updates the transition bits
    // - This must be added outside of the next block
    val updateTransitionBitsDefinition: Option[ProcedureDecl] =
      constructTransitionBuilderProcedure(
        hoaData,
        currentState,
        transitionBits
      )
    // call the update Transition Bits function
    val updateTransitionBitsCall: Option[ProcedureCallStmt] =
      hoaData.moduleVarIdentifiers.map(varIDs =>
        ProcedureCallStmt(
          id =
            updateTransitionBitsId, // this is the ID defined in the function.
          callLhss = List(LhsId(transitionBits)),
          args = varIDs.toList,
          instanceId = None,
          moduleId = None
        )
      )

    // Now assign the next state. We use a havoc that is limited by 2 assumes:
    // 1: that the havoc is within range of the vector
    // 2: that the bit indexed by the next state havoc is 1 (ie we can go to that state)
    val nextState = OperatorApplication(GetNextValueOp(), List(currentState))
    // assume to ensure the havoc is a valid index within the valid bits vector
    val isInRangeAssumes: Option[List[Statement]] =
      hoaData.numStates.map(nStates =>
        List[Statement](
          AssumeStmt(
            OperatorApplication(IntGEOp(), List(nextState, IntLit(0))),
            None
          ),
          AssumeStmt(
            OperatorApplication(IntLTOp(), List(nextState, IntLit(nStates))),
            None
          )
        )
      )
    // assume to ensure that the bit indexed by the havoc var is a 1
    val isValidTransitionAssume = AssumeStmt(
      OperatorApplication(
        EqualityOp(),
        List(
          BitVectorLit(1, 1),
          OperatorApplication(
            VarExtractOp(VarBitVectorSlice(IntLit(1), IntLit(1), Some(1))),
            List(transitionBits)
          )
        )
      ),
      None
    )
    // statement to update the next state havoc -- TODO: Rename to havocState
    val updateState = List[Statement](HavocStmt(HavocableId(currentState)))

    val nextDecl: Option[NextDecl] =
      for {
        isInRangeAssumes <- isInRangeAssumes
        transitionBitsDecl <- transitionBitsDecl
        updateTransitionBitsCall <- updateTransitionBitsCall
      } yield NextDecl(
        BlockStmt(
          List(transitionBitsDecl),
          List(
            updateTransitionBitsCall
          ) ++ updateState ++ isInRangeAssumes ++ List(
            isValidTransitionAssume
          )
        )
      )

    /** 3.5: Spec Properties -- we want the automata to never have current state
      * be a state in the acceptance set.
      */
    // Giant OR conjunction? Giant OR conjunction.
    // Essentially: currentState == acceptSet[0] || currentState == acceptSet[1] || ... and so on.
    // could probably do this using a bitvector, but then we would need to preconstruct and the UCLID tutorial is not specific on
    // how the endian-ness of inputs to bitvectors works. This should work fine... probably.
    val isInAcceptStateExpression: Option[Expr] = hoaData.acceptSets.map(sets =>
      OperatorApplication(
        DisjunctionOp(),
        sets(0)
          .map(state =>
            OperatorApplication(EqualityOp(), List(currentState, IntLit(state)))
          )
          .toList ++ List(BoolLit(false))
      )
    )
    // TODO: Similarly to earlier usage of Disjunction Ops, we need to put an extra 'false' in here in case there is only one acceptState.
    // Similarly to above, this hack must be cleansed with fire at the earliest convenience.

    // ~(isInAcceptStateExpression)
    val neverHitAcceptStateExpression: Option[Expr] =
      isInAcceptStateExpression.map(e =>
        OperatorApplication(NegationOp(), List(e))
      )
    val neverHitAcceptStateSpecDecl: Option[SpecDecl] =
      neverHitAcceptStateExpression.map(e =>
        SpecDecl(
          Identifier(
            originModule.id.toString() + "__" + spec.id
              .toString() + "__automata_property"
          ),
          e,
          List()
        )
      )

    /** sdfsd 4: Module Assembly
      */
    // Note that the module decls list is an ordered list -- ordering of these decls matters.
    val moduleDecls: Option[List[Decl]] =
      for {
        initDecl <- initDecl // Option[InitDecl]
        inputVarDecls <- compatVarDecls
        nextDecl <- nextDecl
        neverHitAcceptStateSpecDecl <- neverHitAcceptStateSpecDecl
        updateTransitionBitsDefinition <- updateTransitionBitsDefinition
      } yield List[Decl](typeImportDecl) ++ inputVarDecls ++ List[Decl](
        currentStateVarDecl,
        initDecl,
        updateTransitionBitsDefinition,
        nextDecl,
        neverHitAcceptStateSpecDecl
      ) // all are Decl, list type is Decl

    val spotModule: Option[Module] = moduleDecls.map(mDecls =>
      Module(
        id = LTLAutomataGenerator.getAutomataIDFromSpec(spec),
        decls = mDecls,
        cmds = originModule.cmds,
        notes = Annotation.default
      )
    )
    println(
      "Ofek Debug: Completed Module: " + spotModule.getOrElse(Nil).toString()
    )
    return spotModule

  }

}
